export const defaultInputStyles: React.CSSProperties = {
  display: "flex",
  width: "300px",
  padding: "0.375rem 0.75rem",
  fontSize: "1rem",
  fontWeight: "400",
  lineHeight: "1.5",
  color: "#212529",
  background: "#fff",
  border: "1px solid #ced4da",
  borderRadius: "0.25rem",
  transition: "border-color 0.15s ease-in-out, box-shadow 0.15s ease-in-out",
  marginBottom: "1rem",
  marginTop: "1rem",
  marginRight: "1rem",
  marginLeft: "1rem",
  cursor: "pointer",
  boxSizing: "border-box",
  fontFamily: "inherit",
};
